config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }
  root to: 'homes#top'
  get "home/about" => "homes#about"
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index]
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :show]
  get 'users/:id/follows' => 'users#follows', as: 'user_follows'
  get 'users/:id/followers' => 'users#followers', as: 'user_followers'
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  get 'search' => 'search#search', as: 'search'



end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :content, presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, {only:[:destroy]}

  def ensure_correct_user
    if current_user != Message.find(params[:id]).user
      redirect_back(fallback_location: user_path(current_user))
    end
  end

  def create
    if UserRoom.where(user_id: current_user.id, room_id: params[:message][:room_id]).present?
      message = Message.new(params.require(:message).permit(:user_id, :content, :room_id).merge(user_id: current_user.id))
      @room = Room.find_by(id: message.room_id)
      @messages = Message.where(room_id: @room.id)
      @message = Message.new
      if message.save
        render :index
      end
    else
      redirect_back(fallback_location: user_path(current_user))
    end
  end

  def destroy
    message = Message.find(params[:id])
    @room = Room.find_by(id: message.room_id)
    @messages = Message.where(room_id: @room.id)
    @message = Message.new
    if message.delete
      render :index
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_message.html.erb
<div class="chat-messages">
    <% if messages.present? %>
      <% messages.each do |message| %>
        <%= message.user.name %>
        「<%= message.content %>」
        <% if current_user == message.user %>
          <%= link_to 'delete', message_path(message.id), method: :delete, remote: true %>
        <% end %>
        <br />
      <% end %>
    <% else %>
      <p class="text-info">...No message yet...</p>
    <% end %>
  </div>
  <div class="send-message">
    <%= form_with model: message, remote: true do |f| %>
      <%= f.text_field :content %>
      <%= f.hidden_field :room_id, :value => room.id %>
      <br>
      <%= f.submit "投稿する" %>
    <% end %>
  </div>

app/views/messages/index.js.erb
$('.chatting').html("<%= j(render 'messages/message', messages: @messages, message: @message, room: @room) %>");
$(".text_field").val("");