config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }
  root to: 'homes#top'
  get "home/about" => "homes#about"
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index]
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :show]
  get 'users/:id/follows' => 'users#follows', as: 'user_follows'
  get 'users/:id/followers' => 'users#followers', as: 'user_followers'
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  get 'search' => 'search#search', as: 'search'



end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :body, presence: true
  attachment :profile_image
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :ensure_correct_user, {only:[:destroy]}

  def ensure_correct_user
    if current_user.id != Comment.find(params[:id]).user_id && current_user.id != Book.find(params[:book_id]).user_id
      flash[:notice] = "The access is forbidden."
      redirect_to books_path
    end
  end

  def create
    @book = Book.find(params[:book_id])
    @comments = Comment.where(book_id: params[:book_id])
    @comment = Comment.new
    comment = Comment.new(comment_params)
    comment.user_id = current_user.id
    comment.book_id = params[:book_id]
    if comment.save
      render :index
    end

  end

  def destroy
    @book = Book.find(params[:book_id])
    @comments = Comment.where(book_id: params[:book_id])
    @comment = Comment.new
    comment = Comment.find_by(id: params[:id], book_id: params[:book_id])
    if comment.delete
      render :index
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment-body">
  <h3 class="border-bottom w-50">comments</h3>
    <% if comments.count != 0 %>
      <% comments.each do |comment| %>
        <table>
          <tr id="comment-<%= comment.id %>">
            <td><%= attachment_image_tag comment.user, :profile_image, format: 'jpeg', fallback:"no_image.jpg", size: "30x30" %>
                <%= link_to comment.user.name, user_path(comment.user.id) %></td>
            <td class="w-75 border-bottom">: <%= comment.body %></td>
            <% if current_user == comment.user || current_user == book.user %>
              <td><%= link_to "destroy", book_comment_path(book.id, comment.id), method: :delete, remote: true, class:"btn btn-outline-warning btn-sm" %></td>
            <% end %>
          </tr>
        </table>
      <% end %>
    <% else %>
      <p class="text-info">.....No comment yet.....</p>
    <% end %>
</div>
<div class="new-comment mt-3">
  <%= form_with(model:[book, comment], remote: true) do |f| %>
    <label for="inputComment">Send a new comment:</label></br>
    <%= f.text_field :body, class:"w-75", id: "inputComment", placeholder:"your comment" %>
    <%= f.submit "Send", class:"btn btn-light btn-sm mb-1" %>
  <% end %>
</div>

app/views/comments/index.js.erb
$('.comments').html("<%= j(render 'comments/comment', book: @book, comments: @comments, comment: @comment) %>");
$(".text_field").val("");