config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }
  root to: 'homes#top'
  get "home/about" => "homes#about"
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index]
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :show]
  get 'users/:id/follows' => 'users#follows', as: 'user_follows'
  get 'users/:id/followers' => 'users#followers', as: 'user_followers'
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  get 'search' => 'search#search', as: 'search'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, {presence: true, length: {maximum: 200}}
  attachment :profile_image
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :body, presence: true
  attachment :profile_image
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :content, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  
  has_many :user_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :email, uniqueness: true
  validates :name, {uniqueness: true, length: {in: 2..20}}
  validates :introduction, length: {maximum: 50}

  attachment :profile_image

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, {only:[:edit, :update, :destroy]}

  def ensure_correct_user
    if current_user.id != Book.find(params[:id]).user_id
      flash[:notice] = "The access is forbidden."
      redirect_to books_path
    end
  end

  def index
    @books = Book.page(params[:page]).reverse_order.per(7)
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] ="You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.page(params[:page]).reverse_order.per(7)
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find_by(id: @book.user_id)
    @comments = Comment.where(book_id: params[:id])
    @comment = Comment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] ="You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.delete
    flash[:notice] = "you have deleted #{book.title} successfully."
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end



end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :forbid_login_user, {only: [:top]}


  def top
  end

  def about
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def create
    @room = Room.create
    @entry1 = UserRoom.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = UserRoom.create(params.require(:user_room).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to room_path(@room.id)
  end

  def show
    @room = Room.find(params[:id])
    if UserRoom.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.user_rooms
    else
      redirect_back(fallback_location: user_path(current_user))
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, {only:[:edit, :update]}

  def ensure_correct_user
    if current_user != User.find(params[:id])
      flash[:notice] = "The access is forbidden."
      redirect_to user_path(current_user.id)
    end
  end


  def show
    @user = User.find(params[:id])
    @books = Book.where(user_id: params[:id]).page(params[:page]).reverse_order.per(7)
    # 以下DM機能
    @currentUserEntries = UserRoom.where(user_id: current_user.id)
    @userEntries = UserRoom.where(user_id: @user.id)
    if @user == current_user
    else
      @currentUserEntries.each do |cuEntry|
        @userEntries.each do |uEntry|
          if cuEntry.room_id == uEntry.room_id
            @isRoom = true
            @roomId = cuEntry.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @user_room = UserRoom.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def index
    @users = User.all
  end

  def follows
    @user = User.find(params[:id])
    @users = @user.following_user
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.follower_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error.html.erb
<% if book.errors.any? %>
  <%= book.errors.count %> errors prohibited this obj from being saved:</br>
  <% book.errors.full_messages.each do |message| %>
  ・<%= message %>
  <% end %>
<% end %>

app/views/books/_list.html.erb
 <table class="table table-striped">
  <thead>
    <tr>
      <td></td>
      <td class="font-weight-bold">Title</td>
      <td class="font-weight-bold">Opinion</td>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user.id) do %>
            <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size: "60x60" %>
          <% end %>
        </td>
        <td><%= link_to "#{book.title}", book_path(book.id) %> </td>
        <td class="ml-5"><%= book.body %></td>
        <td>
          <span id="favorite-button-<%= book.id %>">
            <%= render "favorites/favorite-btn", book: book %>
          </span>
        </td>
        <td>
          <% if Comment.where(book_id: book.id).count != 0 %>
            <i class="fas fa-comments"></i><%= Comment.where(book_id: book.id).count %>
          <% end %>
        </td>
      </tr>
    <% end %>

  </tbody>

</table>
<%= paginate books %>

app/views/books/_side.html.erb
<div class="sidebar pr-5">
  <div class="side-top">
    <% if @user && @user != current_user %>
      <div class="user-info">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
        <h5 class="border-top mt-3 pt-1">name: <%= @user.name %> </h5>
        <h5 class="border-top pt-1">introduction: <%= @user.introduction %></h5>
        <h5 class="border-top pt-1">
          follows:
          <%= link_to user_follows_path(@user) do %>
            <%= Relationship.where(follower: @user).count %>
          <% end %>
        </h5>
        <h5 class="border-top pt-1">
          followers:
          <%= link_to user_followers_path(@user) do %>
            <%= Relationship.where(followed: @user).count %>
          <% end %>
        </h5>
      </div>
      <div class="follow-button">
        <% if current_user.following?(@user) %>
          <%= link_to 'フォロー解除', unfollow_path(@user.id), method: :post, class: 'btn btn-danger' %>
        <% else %>
          <%= link_to 'フォローする', follow_path(@user.id), method: :post, class: 'btn btn-success' %>
        <% end %>
      </div>
      <div class="start-chat mt-2">
        <% if @isRoom == true %>
        　<%= link_to 'チャットへ', room_path(@roomId) %>
        <% else %>
          <%= form_with model: @room do |f| %>
            <%= fields_for @user_room do |e| %>
              <%= e.hidden_field :user_id, :value => @user.id %>
            <% end %>
            <%= f.submit "チャットを始める"%>
          <% end %>
        <% end %>
      </div>
    <% else %>
      <div class="user-info">
        <h2>User info</h2>
        <%= attachment_image_tag current_user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
        <h5 class="border-top mt-3 pt-1">name: <%= current_user.name %> </h5>
        <h5 class="border-top pt-1">introduction: <%= current_user.introduction %></h5>
        <h5 class="border-top pt-1">
          follows:
          <%= link_to user_follows_path(current_user) do %>
            <%= Relationship.where(follower: current_user).count %>
          <% end %>
        </h5>
        <h5 class="border-top pt-1">
          followers:
          <%= link_to user_followers_path(current_user) do %>
            <%= Relationship.where(followed: current_user).count %>
          <% end %>
        </h5>
      </div>
      <div class="edit-info mt-4">
        <%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary btn-block" do%>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="side-bottom mt-4">
    <div class="new-book">
      <h1 class="mb-0">New book</h1>
      <div class="new-book-form border border-primary p-2">
        <%= form_with model:Book.new, local:true do |f| %>
          <h4>Title</h4>
          <%= f.text_field :title, class:"form-control" %>
          <h4>Opinion</h4>
          <%= f.text_area :body, class:"form-control" %></br>
          <%= f.submit 'Create Book', class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/edit.html.erb
<div class="book-error-message">
  <%= render 'books/error', book: @book %>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1 class="border-bottom">Editing Book</h1>
      <div class="update-book">
        <%= form_with model:@book, local:true do |f| %>
          <h4>Title</h4>
          <%= f.text_field :title, autofocus: true, class: "form-control" %>
          <div class="mt-4">
          <h4>Opinion</h4>
            <%= f.text_area :body, autofocus: true, class: "form-control" %></br>
          </div>
          <%= f.submit 'Update Book', class: "btn btn-success" %>
        <% end %>
      </div>
      <div class="link">
        <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="book-error-message">
  <%= render 'books/error', book: @book %>
</div>

<div class="container">
  <div class="row">
    <div class="side col-md-3">
      <%= render 'books/side' %>
    </div>
    <div class="book-table col-md-8 offset-md-1 w-75">
      <h1>Books</h1>
      <%= render 'books/list', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="side col-md-3">
      <%= render 'books/side' %>
    </div>
    <div class="col-md-8 offset-md-1 w-75">
      <h1 class="border-bottom">Book detail</h1>
      <div class="book-detail d-flex justify-content-start">
        <%= link_to user_path(@user.id) do %>
          <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "60x60" %></br>
          <%= @user.name %>
        <% end %>
        <div class="detail-content-title pt-2">
          <h6 class="ml-5 text-primary"><%= @book.title %></h6>
        </div>
        <div class="detail-content-body pt-2">
          <h6 class="mx-5"><%= @book.body %></h6>
        </div>
        <div class="comments-count mx-5 pt-2">
          コメント数<i class="fas fa-comments"></i>：<%= Comment.where(book_id: @book.id).count %>
        </div>
        <div class="edit-delete ml-5 mt-2">
          <% if current_user == @user %>
            <%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-outline-secondary" %>
            <span class="ml-2">
              <%= link_to "Destroy", book_path(@book.id), method: :delete, class: "btn btn-danger" %>
            </span>
          <% end %>
        </div>
      </div>
      <div class="favorite mt-3">
        <span class="favorite-button">
          <%= render "favorites/favorite-btn", book: @book, comments: @comments %>
        </span>
        <span class="who-likes ml-4">
          <span class="text-white bg-secondary">Who likes? ...</span>
          <span class="bg-light text-dark ml-2">
            <% Favorite.where(book_id: @book).each do |favo| %>
              <i class="fas fa-heart"></i><%= User.find_by(id: favo.user_id).name %>
            <% end %>
          </span>
        </span>
      </div>
      <div class="comments mt-5">
        <%= render 'comments/comment', book: @book, comments: @comments, comment: @comment %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="who-chattiong">
  <h1>
  参加者...
  <% @entries.each do |e| %>
    <i class="fas fa-user"></i><%= e.user.name %>
  <% end %>
  </h1>
</div>
<div class="chatting">
  <%= render 'messages/message', messages: @messages, message: @message, room: @room %>
</div>