config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
   }
  root to: 'homes#top'
  get "home/about" => "homes#about"
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index]
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :show]
  get 'users/:id/follows' => 'users#follows', as: 'user_follows'
  get 'users/:id/followers' => 'users#followers', as: 'user_followers'
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  get 'search' => 'search#search', as: 'search'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, {presence: true, length: {maximum: 200}}
  attachment :profile_image
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :body, presence: true
  attachment :profile_image
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :content, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  
  has_many :user_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates :email, uniqueness: true
  validates :name, {uniqueness: true, length: {in: 2..20}}
  validates :introduction, length: {maximum: 50}

  attachment :profile_image

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, {only:[:edit, :update, :destroy]}

  def ensure_correct_user
    if current_user.id != Book.find(params[:id]).user_id
      flash[:notice] = "The access is forbidden."
      redirect_to books_path
    end
  end

  def index
    @books = Book.page(params[:page]).reverse_order.per(7)
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] ="You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.page(params[:page]).reverse_order.per(7)
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find_by(id: @book.user_id)
    @comments = Comment.where(book_id: params[:id])
    @comment = Comment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] ="You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.delete
    flash[:notice] = "you have deleted #{book.title} successfully."
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end



end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :forbid_login_user, {only: [:top]}


  def top
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
        <div class="top-menu d-flex w-100">
          <div class="logo flex-grow-1">
            <% if current_user %>
              <a class="navbar-brand py-2 ml-5"><i class="fas fa-atlas"></i>Bookers</a>
            <% else %>
              <a class="navbar-brand py-2 ml-5" href="/"><i class="fas fa-atlas"></i>Bookers</a>
            <% end %>
          </div>
          <!--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#topNav" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">-->
          <!--  <span class="navbar-toggler-icon"></span>-->
          <!--</button>-->
          <div id="topNav">
            <ul class="navlist nav">
              <% if user_signed_in? %>
                <li class="nav-item ml-4">
                  <%= link_to user_path(current_user.id) do %>
                    <p><i class="fas fa-home"></i>Home</p>
                  <% end %>
                </li>
                <li class="nav-item ml-4">
                  <%= link_to users_path do%>
                    <p><i class="fas fa-users"></i>Users</p>
                  <% end %>
                </li>
                <li class="nav-item ml-4">
                  <%= link_to books_path do %>
                    <p><i class="fas fa-book-open"></i>Books</p>
                  <% end %>
                </li>
                <li class="nav-item ml-4">
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <p><i class="fas fa-sign-out-alt"></i>logout</p>
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to root_path do %>
                    <p><i class="fas fa-home"></i>Home</p>
                  <% end %>
                </li>
                <li class="nav-item ml-3">
                  <%= link_to "/home/about" do %>
                    <p><i class="fas fa-link"></i>About</p>
                  <% end %>
                </li>
                <li class="nav-item ml-3">
                  <%= link_to new_user_registration_path do %>
                   <p><i class="fas fa-user-plus"></i>sign up</p>
                  <% end %>
                <li class="nav-item ml-3">
                  <%= link_to new_user_session_path do %>
                    <p><i class="fas fa-sign-in-alt"></i>login</p>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="searching d-flex justify-content-center">
      <% if current_user %>
        <%= form_with url: search_path, method: :get, local: true do |f| %>
          <%= f.text_field 'search[content]' %>
          <%= f.select 'search[model]', options_for_select({"User" => "user", "Book" => "book"}) %>
          <%= f.select 'search[how]', options_for_select({"完全一致" => "match", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial"}) %>
          <%= f.submit :検索 %>
        <% end %>
      <% end %>
    </div>
    <div class="flash">
      <% if flash[:notice] %>
        <%= flash[:notice] %>
      <% end %>
    </div>
    <div class="p-3">
      <%= yield %>
    </div>
  </body>
</html>